# Generated by Django 4.0.4 on 2022-04-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Post',
        ),
    ]
